### ISSUE TITLE
Would you complete the tutorial?

### ISSUE THREAD

**Issue by AkatQuas** [antoaravinth/lets-build-express#5]
Thanks a lot for the wonderful work you have done! 🎉🎉🎉

I have learnt a lot reading the chapter 1-5, understood more about the working procedure in express.

Maybe you are buried by the heavy work, but please, I do beg you to complete the tutorial on `building express`.

Please, tell me you would complete the tutorial.

**Comment by antsmartian** [comment]
Hey thanks for your kind words. 

Sorry I was busy and didn't find time to write up the upcoming chapters. But yeah, will definitely close this, when I get free time!
